[package]
name = "actix-jwks-auth-middleware"
version = "0.1.0"
authors = ["Colin Flanagan <colin.flanagan-morgan@modaoperandi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
